"""
Django settings for mock_test project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gf)&q^!_5_oz@s(bqb*^zkpwqrtscb^ksxwj1+ak8yf6^we@nc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.main',
    'apps.api',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'pyclick',
    'apps.basic',
]

CORS_ALLOW_METHODS = (
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
)

CORS_ALLOW_HEADERS = (
    "x-requested-with",
    "accept",
    'origin',
    "authorization",
    "x-csnftoken",
    "token",
    "x-device-id",
    'x-device-type',
    "x-push-id",
    "dataserviceversion",
    'maxdataservicevension',
)

CORS_ORIGIN_ALLOW_ALL = True

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mock_test.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mock_test.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'postgresql://gen_user:King%23%2311@109.172.90.230:5432/default_db',
        'NAME': 'mock_test',
        'USER': 'desmon',
        'PASSWORD': 'King##11',
        'HOST': '109.172.89.216',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'main.User'



CSRF_TRUSTED_ORIGINS = ['https://76d4-89-236-226-231.ngrok-free.app']

DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_MEMORY_SIZE = None

CORS_ALLOWED_ORIGINS = ['https://76d4-89-236-226-231.ngrok-free.app']
CORS_ALLOW_ALL_ORIGINS = True


# PAYME: dict = {
#     'PAYME_ID': '',
#     'PAYME_KEY': '',
#     'PAYME_URL': 'checkout.paycom.uz/',
#     'PAYME_CALL_BACK_URL': 'https://3da7-89-236-229-146.ngrok-free.app', # merchant api callback url
#     'PAYME_MIN_AMOUNT': '500', # integer field
#     'PAYME_ACCOUNT': 'order_id',
# }
#
# ORDER_MODEL = 'api.models.Order'

# PAYCOM_SETTINGS = {
#     "KASSA_ID": "",  # token
#     "TOKEN": "",  # password
#     "SECRET_KEY": "",  # password
#     "ACCOUNTS": {
#         "KEY": "id"
#     }
# }


CLICK_SETTINGS = {
    'service_id': "31090",
    'merchant_id': "23197",
    'secret_key': "yxUgWNLyPO",
    'merchant_user_id': "37425",
}
